### PR TITLE
Updated Upstream (Pufferfish)

### PR DESCRIPTION
**Pull request by Dreeam-qwq**
Update the upstream, and delete these patches below that cause compiling errors:
[0101-Fix-a-bunch-of-vanilla-bugs.patch](https://github.com/etil2jz/Mirai/blob/ver/1.19.2/patches/server/0101-Fix-a-bunch-of-vanilla-bugs.patch)
[0103-PaperPR-Set-position-before-player-sending-on-dimens.patch](https://github.com/etil2jz/Mirai/blob/ver/1.19.2/patches/server/0103-PaperPR-Set-position-before-player-sending-on-dimens.patch)
[0108-Run-tasks-while-reading-poi-data.patch](https://github.com/etil2jz/Mirai/blob/ver/1.19.2/patches/server/0108-Run-tasks-while-reading-poi-data.patch)
[0109-Run-tasks-while-we-wait-for-the-entity-storage-worke.patch](https://github.com/etil2jz/Mirai/blob/ver/1.19.2/patches/server/0109-Run-tasks-while-we-wait-for-the-entity-storage-worke.patch)

### CODE REVIEW

**Comment by minhh2792** [comment]
What error ?

**Comment by Dreeam-qwq** [comment]
> What error ?

like, can't resolve symbol xxx, and i don't know how to solve, just delete it.

**Comment by MartijnMuijsers** [comment]
[0101-Fix-a-bunch-of-vanilla-bugs.patch](https://github.com/etil2jz/Mirai/blob/ver/1.19.2/patches/server/0101-Fix-a-bunch-of-vanilla-bugs.patch) and [0103-PaperPR-Set-position-before-player-sending-on-dimens.patch](https://github.com/etil2jz/Mirai/blob/ver/1.19.2/patches/server/0103-PaperPR-Set-position-before-player-sending-on-dimens.patch) have already been merged, so can be deleted.

[0108-Run-tasks-while-reading-poi-data.patch](https://github.com/etil2jz/Mirai/blob/ver/1.19.2/patches/server/0108-Run-tasks-while-reading-poi-data.patch) and [0109-Run-tasks-while-we-wait-for-the-entity-storage-worke.patch](https://github.com/etil2jz/Mirai/blob/ver/1.19.2/patches/server/0109-Run-tasks-while-we-wait-for-the-entity-storage-worke.patch) would be nice to be rebased correctly. Instead of `world.chunkSource.mainThreadProcessor` there is `world.chunkTaskScheduler.mainThreadExecutor` now, should be doable I hope!

**Comment by minhh2792** [comment]
> > What error ?
> 
> like, can't resolve symbol xxx, and i don't know how to solve, just delete it.

That is not how you resolve conflicts

**Comment by etil2jz** [comment]
Updated in ac99671
I'll take a look at `Run tasks while reading poi data` and `Run tasks while we wait for the entity storage worker` later

**Pull request closed without merging**
